---
### Debian/Ubuntu
- name: "Install | {% if name is defined %}{{ name }} | {% endif %}Make sure repositories are added"
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{% if config.debian is defined and config.debian.repositories is defined %}{{ config.debian.repositories }}{% else %}[]{% endif %}"
  when: ansible_os_family == "Debian"

- name: "Install | {% if name is defined %}{{ name }} | {% endif %}Make sure required packages are installed"
  apt:
    pkg: "{{ item }}"
    state: latest
    force: yes
  with_items: "{% if config.debian is defined and config.debian.packages is defined %}{{ config.debian.packages }}{% else %}[]{% endif %}"
  when: ansible_os_family == "Debian"


### Gentoo
- name: "Install | {% if name is defined %}{{ name }} | {% endif %}Make sure required packages are installed"
  portage:
    package: "{{ item }}"
    state: present
  with_items: "{% if config.gentoo is defined and config.gentoo.packages is defined %}{{ config.gentoo.packages }}{% else %}[]{% endif %}"
  when: ansible_os_family == "Gentoo"